_keybase_secrets: 
  prod: "{{ lookup('file', '/keybase/team/cepro_crep/secrets-prod.yml') | from_yaml }}"
  test: "{{ lookup('file', '/keybase/team/cepro_crep/secrets-test.yml') | from_yaml }}"

keybase_secrets: "{{ _keybase_secrets.get(inventory_environment, None) }}"